spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  main:
    web-application-type: reactive
  jackson:
    serialization:
      indent-output: on
  session:
    timeout: 36000  # in seconds; Goal: same lifetime as SSO Session (e.g. 10 hours)

server:
  port: 8083
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false

management:
  endpoints:
    access:
      default: none
    web:
      cors:
        allowedOrigins:
          - "http://localhost:8085"
          - "http://127.0.0.1:8085"
        allowedMethods: "*"
        allowedHeaders: "*"
        allowCredentials: on
        maxAge: 3600
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
info.application.name: ${spring.application.name}
info.application.version: @project.version@
